-- MySQL Script generated by MySQL Workbench
-- Fri Feb 21 09:47:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Request` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Request` (
  `idRequest` INT NOT NULL AUTO_INCREMENT,
  `navigator` VARCHAR(200) NOT NULL,
  `fromUrl` VARCHAR(200) NULL,
  PRIMARY KEY (`idRequest`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Parameter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Parameter` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Parameter` (
  `idParameter` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `value` VARCHAR(200) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `Request_idRequest` INT NOT NULL,
  PRIMARY KEY (`idParameter`, `Request_idRequest`),
  INDEX `fk_Parameter_Request_idx` (`Request_idRequest` ASC) VISIBLE,
  CONSTRAINT `fk_Parameter_Request`
    FOREIGN KEY (`Request_idRequest`)
    REFERENCES `mydb`.`Request` (`idRequest`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
